### ISSUE TITLE
CacheManagerTest testReuseCacheManagerGetCache

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107tck#104]
Calls on a closed cache:

```
cacheManager.getCache("nonExistent", null, null);
```

However, `Null` is an illegal parameter.

The test expects a `IllegalStateException` however it may be `NullPointerException` as well.
The Spec does not say what exception has priority. The TCK should not do checks with two
error conditions in combination and assert only one reaction.

**Comment by cruftex** [comment]
Another finding:

````
    try {
      cacheManager.createCache("Dog", null);
      fail();
    } catch (IllegalStateException e) {
      //expected
    }
````

This may IMHO yield a NPE or a `IllegalStateException`.

Also found that there are two tests that are identical to another.

- `getOrCreateCache_StatusOK` is identical to  `createCache_StatusOK`
- `getOrCreateCache_Different` is identical to `createCache_Different`

**Comment by vbekiaris** [comment]
Closing this issue, the changes from PR #109 are already merged
