### ISSUE TITLE
Misc Cleanup

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107tck#105]
Issue to address and bundle tiny cleanup changes.

System.out in `org.jsr107.tck.event.CacheListenerTest`

CacheMBStatisticsBeanTest reversed assertEquals:
    assertEquals(result, "Sooty");
    assertEquals(result, "Trinity");

Remove CacheLoaderTest.shouldNotLoadNullEntries and CacheLoaderWriterTest.shouldNotLoadNullEntries
These two tests are 100% identical to the respective tests named 'shouldNotLoadNullValues'.

`CacheLoaderTest` and `CacheLoaderWithoutReadThroughTest` `shouldPropagateExceptionUsingLoadAll`
is missing a `fail()` to complete the exception check idiom.

**Comment by christian-esken** [comment]
I did a quick check, and I counted 3 occurrences of reversed assertEquals in CacheMBStatisticsBeanTest.java. I searched for "assertEquals(result".I extended my search on the whole TCK and found 11 occurences (hopefully without false positives).
- CacheExpiryTest : 6
- CacheWriterTest : 2
- CacheMBStatisticsBeanTest : 3
