### ISSUE TITLE
Unwrap Tests should Fail if Class is not Existing

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107tck#112]
Enrico Olivelli / @eolivelli reported:

> It is incredible that if you misconfigure the CacheManagerImpl system property providing a non-existant class the TCK works fine only ignoring a single test case

Test should fail in that case. If unwrap is not supported by a cache implementation, there should
be a defined parameter that instructs the TCK to skip the test.

**Comment by gregrluck** [comment]
The TCK pom.xml says:


                <CacheManagerImpl>org.jsr107.ri.RICacheManager</CacheManagerImpl>
                <CacheImpl>org.jsr107.ri.RICache</CacheImpl>
                <CacheEntryImpl>org.jsr107.ri.RIEntry</CacheEntryImpl>

You mis-define it and you get a broken test. Seems logical to me.
