### ISSUE TITLE
Missing integration configuration tests

### ISSUE THREAD

**Issue by ljacomet** [jsr107/jsr107tck#113]
# read-through and `CacheLoader` factory

In section 7.2 of the spec, it says (page 64):

> Read-Through caching is set at configuration time by calling setReadThrough(boolean
> isReadThrough) on MutableConfiguration. A CacheLoader Factory must also have been
> defined.

There is currently no TCK test enforcing the _must_ in that last sentence.
# write-through and `CacheWriter` factory

In section 7.3 of the spec, it says (page 66):

> Write-Through caching is set at configuration time by calling setWriteThrough(boolean
> isWriteThrough) on MutableConfiguration. A CacheWriter Factory must also have
> been defined. 

Again, there is currently no TCK test enforcing the _must_ in the last sentence.

Note that per javadoc of `CacheManager.createCache(String, Configuration)`, the expected exception is an `IllegalArgumentException`.

**Comment by cruftex** [comment]
The Spec doesn't say something about the exact semantics of a miss configuration. Adding a TCK test would require a more precise Spec first.

See my comment on this here:
https://github.com/jsr107/jsr107tck/issues/69#issuecomment-194465010

**Comment by cruftex** [comment]
Just a general note. The Spec says:

> A CacheWriter Factory must also have been defined.

That kind of wording is has various ways to be interpreted. Usually, the Spec defines what a cache implementation "must do". Here it defines what a cache client "must do" and leaves the semantics of the cache implementation undefined.

If implementations should have the option to react different on error conditions / miss configuration a better wording would be:

> An ambiguous situation exists when the write through is set to true but no cache writer is defined. The outcome is implementation specific.

**Comment by cruftex** [comment]
This this, since a duplicate.
