### ISSUE TITLE
Missing tag for 1.0.0

### ISSUE THREAD

**Issue by rvansa** [jsr107/jsr107tck#114]
Hello, I am trying to debug some test failures when running TCK from `javax.cache:cache-tests:1.0.0`, but sources are not published to Maven Repository and this repo is missing a tag that could be linked to the artifact. I found out that e5049a4de51c54c2572135d9e4be9a8688b4eaff works for me, but it would be better if you could upload the sources JAR to Maven, too.

**Comment by vbekiaris** [comment]
A [sources jar for 1.0.0 release](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22javax.cache%22%20AND%20a%3A%22cache-tests%22%20AND%20v%3A%221.0.0%22) is currently available on maven central. I created the `v1.0.0` tag in the repository, the `sources.jar` on maven central matches 
https://github.com/jsr107/jsr107tck/commit/e5049a4de51c54c2572135d9e4be9a8688b4eaff as @rvansa identified.
