### ISSUE TITLE
Introduce TCK distribution bundle for TCK licensees

### ISSUE THREAD

**Issue by brianoliver** [jsr107/jsr107tck#116]
The TCK should only be available via download from the JCP once licensees have agreed to the SATCK license.  Once this license is executed a TCK distribution, consisting of the TCK source code, a TCK binary and the TCK Users Guide should be made available in a single explicitly versioned package (zip file).

To facilitate the distribution of the TCK, we need to modify the build so that this is produced automatically so that it may be provided to the JCP for download by licensees.

**Comment by gregrluck** [comment]
Spoke to Brian about this. He thinks wiht the source code header files to the TCK license this should be sufficient.
