### ISSUE TITLE
Faulty tests for non-null Cache returned from getCache

### ISSUE THREAD

**Issue by vbekiaris** [jsr107/jsr107tck#148]
The [specification for `Caching#getCache(String, Class<K>, Class<V>)`](https://github.com/jsr107/jsr107spec/blob/7157ec6cf6b8906cf7e64a21ab29959b2aab7d62/src/main/java/javax/cache/Caching.java#L268-L270) reads:

```
   * Implementations that support declarative mechanisms for pre-configuring
   * {@link Cache}s may return a pre-configured {@link Cache} instead of
   * <code>null</code>.
```

The TCK however includes test `org.jsr107.tck.CachingTest#cachingProviderGetNonExistentCache()` that enforces that an implementation must return `null`. It seems this test should be removed.

Same as above applies for test `org.jsr107.tck.CacheManagerTest#getCache_Missing()` that enforces a `null` return from `CacheManager#getCache(String)`, even though its [javadoc includes the same passage as above](https://github.com/jsr107/jsr107spec/blob/403cb2b86813b18e1febdfa3143724df65b14ad1/src/main/java/javax/cache/CacheManager.java#L208-L210).

**Comment by cruftex** [comment]
Unfortunately the spec is missing a description of a cache life cycle and what expectations are behind it.

>   * Implementations that support declarative mechanisms for pre-configuring
>   * {@link Cache}s may return a pre-configured {@link Cache} instead of
 >  * <code>null</code>.

That means an implementation can create and return a cache that is not yet created for immediate usage (with in memory structures), but it is logically existing in the configuration. This section does not say anything about the behavior if a cache is not existing. Actually it expands the idea of what "existing" means.

> The TCK however includes test org.jsr107.tck.CachingTest#cachingProviderGetNonExistentCache() that enforces that an implementation must return null. It seems this test should be removed.

IMHO the test is okay. The tests expect that all caches are created programmatically and that there is no external configuration. Allowing that there may be any kind of external configuration would break a lot of tests.

**Comment by vbekiaris** [comment]
I see, so "pre-configured" implies that there is some explicit, non-default configuration of cache(s) before they can be created and returned from `getCache`. Closing this issue.
