### ISSUE TITLE
org.jsr107.tck.spi.CachingProviderClassLoaderTest.getCacheManagerSingleton()

### ISSUE THREAD

**Issue by timeck** [jsr107/jsr107tck#61]
Unless I'm mistaken, I think this test case is invalid. In the test case code below the call to `getCacheManager()`  at (1) is supposed to use `CachingProvider#getDefautClassLoader()`. The assertion at (2) will only be valid if  `CachingProvider#getDefautClassLoader()` happens to be same as the TCCL. I don't see how that is mandated to be the case in any way for implementations of `javax.cache.spi.CachingProvider`. The same issue is present in the last assertion of the test method as well

```
  public void getCacheManagerSingleton() {
    ClassLoader contextLoader = Thread.currentThread().getContextClassLoader();

    CachingProvider provider = Caching.getCachingProvider(contextLoader);

    CacheManager manager = provider.getCacheManager();
    assertNotNull(manager);
    assertSame(manager, provider.getCacheManager());  /* (1) */
    assertSame(manager, provider.getCacheManager(provider.getDefaultURI(), contextLoader)); /* (2) */
```

**Comment by chrisdennis** [comment]
I think we're still missing some stuff here.  I've created PR #77 which tries to fix those remaining issues.

**Comment by gregrluck** [comment]
Merged Chris's suggested change.
