### ISSUE TITLE
org.jsr107.tck.management.CacheMBStatisticsBeanTest.testPutIfAbsent()

### ISSUE THREAD

**Issue by timeck** [jsr107/jsr107tck#63]
This test asserts that neither the "hit" or "miss" counts are affected by two `Cache.putIfAbsent()` operations

The spec lists this however (page 131):

operation | Puts | Removals | Hits | Misses
-------------|--------|---------------|-------|----------
boolean putIfAbsent(K key, V value) | Yes | No | Yes | Yes 

I am of the opinion that the first `putIfAbsent()` would count as both a "put" and a "miss", and the second call would record a "hit" in the cache statistics

**Comment by gregrluck** [comment]
Moving this to 1.0.1. Implementations will have to fix their behaviour.
