### ISSUE TITLE
Introduce a new test to confirm ConfigurationExceptions are thrown for illegal configurations

### ISSUE THREAD

**Issue by brianoliver** [jsr107/jsr107tck#69]
Currently we don't have many tests for illegal configurations.  

eg: specifying "read-through" but not specifying a "cache loader factory".

**Comment by cruftex** [comment]
Its part of a product philosophy what may happen and when. When it comes to error and exception handling I often see very different opinions and concepts (from fail fast, fail late, log warning and assume defaults).

For the example:
- Exception is thrown when cache is created / requested first
- Exception is thrown when the loader is needed, if not everything works fine 
- Log a warning and use a default loader that returns null

If we do add TCK checks, we need to add this to the Spec as well.

Instead, adding consistency checks to the RI would be a good idea, so when we update the TCK we do not produce any wrong configuration any more.

Personally, I am a big fan of "fail fast", having a precise exception handling and failing as early as possible is a good idea. I just don't think its a match for every product and situation.

**Comment by gregrluck** [comment]
We have not in the spec insisted on the principal of fail-fast for this. We would need to define illegal configuration options in the spec and then test them with TCK tests. We have not done so in the spec. An issue should be raised against the spec if it is thought we should do that.
