### ISSUE TITLE
CacheWriterException is expected when CacheWriter throws an exception

### ISSUE THREAD

**Issue by sboikov** [jsr107/jsr107tck#72]
Tests where CacheWriter's methods write(All)/delete(All) throw an exception expect that Cache's methods put(All)/remove(All) throw CacheWriterException in this case.
I can not find where the spec requires this behavior, and I think that implementation can throw CacheException in this case, not CacheWriterException.

List of tests which expect CacheWriterException if CacheWriter throws an exception:
CacheWriterTest.shouldNotPutWhenWriteThroughFails
CacheWriterTest.shouldWriteThoughUsingPutAll_partialSuccess
CacheWriterTest.shouldNotRemoveWhenWriteThroughFails
CacheWriterTest.shouldWriteThroughRemoveAll_partialSuccess
CacheWriterTest.shouldWriteThroughRemoveAllSpecific_partialSuccess
CacheWriterTest.shouldWrapWriterExceptions

I believe it is safe to change these tests to catch CacheException instead of CacheWriterException, this change won't break any existing implementation.

**Comment by dsetrakyan** [comment]
Can someone from JSR respond here?

**Comment by gregrluck** [comment]
The specification consists of the API, JavaDoc plus the spec document. The JavaDoc clearly state that CacheWrite failures should through a CacheWriterException. So if something else is the problem it should be wrapped in a CacheWriteException. 

So the tests are checking the correct behaviour.

**Comment by sboikov** [comment]
Thanks for clarification, closing this issue.
