### ISSUE TITLE
License mismatch with JSR details

### ISSUE THREAD

**Issue by keilw** [jsr107/jsr107tck#75]
Hi,

The LICENSE.txt file here says "Apache 2.0 License" but on https://jcp.org/en/jsr/detail?id=107 the Final TCK License is said to be: https://jcp.org/aboutJava/communityprocess/licenses/jsr107/SA-TCK-JSR-107-10_22_12.pdf

For the RI it looks OK, but here maybe the RI license was "forgotten" in the GitHub repo. Hope this can be fixed with a MR, too (it's not a functional issue but gives a wrong impression to users)

Cheers,
Werner

**Comment by gregrluck** [comment]
Werner the TCK license is the normal JCP TCK license. The RI is Apache 2. That is not a mistake. It is permissible.

**Comment by keilw** [comment]
Is Apache 2 "the normal TCK license"?;-)
This file https://github.com/jsr107/jsr107tck/blob/master/LICENSE.txt states, that the TCK was licensed under the Apache 2.0 license, not "the normal JCP TCK license". That's the mismatch. I am not talking about the RI which looks OK.

**Comment by keilw** [comment]
Also in the POM
 <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

So as of now, BOTH say Apache 2.0 which contradicts your statement above. IMHO the ticket is not closed, till LICENSE.txt is removed and either the <license> entry of the POM is just removed or the URL and name pointing to the same documents as the JSR detail page.

**Comment by keilw** [comment]
Hope you can fix it, I don't want to bother creating another ticket (will have to since this can't be reopened, if it's not resolved)
