### ISSUE TITLE
Relax JMX Statistics Testing in accordance with the Specification

### ISSUE THREAD

**Issue by brianoliver** [jsr107/jsr107tck#79]
The manner in which the JMX tests are currently written assume statistics are updated instantly.   This is not a requirement of the specification.

**Comment by chrisdennis** [comment]
I'm sure I raised this during initial discussion on the statistics aspects of the spec but I'll restate it now since it's relevant.  The current way that statistics is specified makes it completely untestable.  The spec states:

> There are no defined consistency semantics for statistics. Refer to the implementation for precise semantics.

To me this means the TCK cannot assume that the statistics are ever updated... hence no assertions can be made.

**Comment by brianoliver** [comment]
Perhaps we need a "switch" in the TCK that defines what is a "reasonable period of time".

I mean, surely we should be able to expect that a JCache implementation will update JMX statistics at some point in time, something that is reasonable?   We can then simply make a assumption / good guess  as to what is "reasonable".

This at least is a practical approach to moving forward?

Perhaps the SPEC document should be updated to state that the frequency of update may be configurable, but how that occurs is outside the scope of the specification?

**Comment by chrisdennis** [comment]
The main problem here is that the TCK can only test against "testable assertions" but in the realm of statistics monitoring many people would actually tolerate a much looser set of guarantees - what the implementation judges to be good enough, even if it isn't testable is often good enough.  I don't know if there is a good answer to this now... we have a statistics API that is extremely strict in many respects and is therefore very tempting to test, but is extremely loose in others, making it currently untestable.  The thought of having the TCK invoke a bunch of implementation specific code to make stats testable gives me the heebie jeebies, I think I might prefer no test coverage on stats at all.

**Comment by cruftex** [comment]
I would be fine, when the standard specifies the statistics are updated on a defined event.

However we cannot add new methods. My suggestion would be Cache.clear() that is a low frequency event, that is supposed to free resources so most likely the statistics need to be update anyway.

I am not quite sure whether some implementations reset the statistics on clear, or what the standard says about this. I will find this out and comment on this later.

**Comment by cruftex** [comment]
Update on using Cache.clear() as signal to flush the statistics:

The TCK explicitly checks right now that the statistics are not changed after a Cache.clear(). So it is feasible to change the TCK that it issues a Cache.clear() before checking the statistics counters. This allows implementations to postpone updates until they receive a Cache.clear().

**Comment by cruftex** [comment]
Update on using Cache.clear() as signal to flush the statistics:

Possible change is here:

https://github.com/cruftex/jsr107tck/commit/7f339b09f45d081969b0ed4dbb5f71d8d34595a2

Tested this TCK modification against RI, hazelcast, EHCache, Apache Ignite, Apache JCS. The only test that fails is

 testPutIfAbsent(org.jsr107.tck.management.CacheMBStatisticsBeanTest): expected:<1> but was:<0>

The change works completely with the SNAPSHOT RI.

**Comment by cruftex** [comment]
Meanwhile I tested the proposed change also against Oracle Coherence. It works also. Only the test testPutIfAbsent fails, which was previously changed in https://github.com/jsr107/jsr107tck/issues/63

The proposed change can go in, without impacting existing implementations.

**Comment by cruftex** [comment]
Opened PR.

**Comment by ljacomet** [comment]
This seems very wrong to attach extra semantic to an operation, especially when there is such a disconnect between the two.

**Comment by chrisdennis** [comment]
This doesn't make the situation nay better.  You're still relying on inspected behavior in these tests.  Previously the unspecified behavior was "the statistics get updated quick enough that this test won't fail", now the unspecified behavior is "the statistics get forcibly flushed when clear is called on the associated cache".  Unless we modify the specification to make one of these required behavior, there is no value in making this change - it moves us from one broken situation to a different one. I still stand by my original assertion that for better or worse statistics is not testable - and I'm not convinced this is such a big deal... lets just delete the tests and move on.

**Comment by cruftex** [comment]
We can add to the specification:

> Cache implementations may delay the update of statistics or update the statistics synchronous
> to the operation. If the implementation delays statistics update it must ensure that statistics will be
> updated to the latest values on the operation `Cache.clear()`

Chris's objection is correct, the Spec says nothing about when statistics are updated.

I did chose `clear()` since an implementation would clear up buffers and temporary data as well as flush statistics anyways on that command.

**Comment by cruftex** [comment]
@chrisdennis, @ljacomet : ping!

**Comment by ljacomet** [comment]
> I did chose `clear()` since an implementation would clear up buffers and temporary data as well as flush statistics anyways on that command

That is pure implementation detail that feels very wrong to make mandatory at the specification level.

Specifying statistics timing in order to enable predictable testing seems the wrong approach

**Comment by cruftex** [comment]
> Specifying statistics timing in order to enable predictable testing seems the wrong approach

Totally right. The TCK is assuming an instant update right now. That is timing as well. So the only other option would be to remove the statistic tests completely.

I tried what Brian suggested:

> This at least is a practical approach to moving forward?

There is no perfect solution. I fear that a proposal to remove the statistics tests completely will get more rejections.

**Comment by cruftex** [comment]
Ah, actually we could just require what we just found out:

> Cache implementations may delay the update of statistics or update the statistics synchronous
> to the operation. Testing the statistics is covered by the TCK. In order to test statistic counters
> the TCK assumes that statistics are updated to the latest values when receiving a `Cache.clear()`.
> This behavior is not required. Implementations may exclude the relevant tests.

Thoughts?

**Comment by cruftex** [comment]
So far we have these options:

a) Keep it as is
b) make statistics optional in the Spec
c) remove statistics testing from the TCK
d) require that statistics are flushed at some point to make it testable; but this should not be a mandatory semantic

Discussion:
b) No; that would be a major change
c) This is actually similar to making statistics optional. Everybody claims JSR107 with passing 100% of the TCK.
d) This would introduce non-normative requirement in the Spec for testing and it is still a hacky solution.

I have another idea:

In case the statistics do not have the correct values, we wait until timeout. By default it is reasonably high (I suggest one minute). The timeout is configurable by a system property, so developers can lower the timeout to get faster feedback.

We add this to the spec:

> The update of statistics may be delayed. The maximum expected update delay is one minute.
> Cache implementations may have a higher update lag, but must document it.
> After a `Cache.clear()` cache implementation should update the statistics to the latest values.

Anyhow, changing the TCK statistic tests is quite some work and I don't think it is the highest priority. So if there is no `+1` on some way we can go, or no interest at all, I`ll close the issue and we keep it as is for now.

**Comment by vbekiaris** [comment]
I prepared a PR (#124) for this issue that implements the "statistics updated within timeout" suggestion. Could someone review the PR?
