### ISSUE TITLE
Remove "Apache 2" license from TCK

### ISSUE THREAD

**Issue by keilw** [jsr107/jsr107tck#80]
As stated in the JSR detail page and confirmed by @gregrluck in https://github.com/jsr107/jsr107tck/issues/75 the TCK uses https://jcp.org/aboutJava/communityprocess/licenses/jsr107/SA-TCK-JSR-107-10_22_12.pdf, not the Apache 2.0 Lisence.
However, https://github.com/jsr107/jsr107tck/blob/master/LICENSE.txt
and the "licenses" section of the TCK POM both wrongly state the TCK was licensed under Apache 2.0 This sounds like a copy/paste mistake from the RI, but in this case, RI and TCK do not use exactly the same license. Please fix.

**Comment by keilw** [comment]
Also according to the JSR detail page https://jcp.org/en/jsr/detail?id=107 the Final TCK License is:
https://jcp.org/aboutJava/communityprocess/licenses/jsr107/SA-TCK-JSR-107-10_22_12.pdf, see above, not the Apache 2.0 License. While all versions published on MavenCentral, including 1.0.1 http://mvnrepository.com/artifact/javax.cache/tck-parent/1.0.1 say they're licensed under Apache 2.0.

**Comment by cruftex** [comment]
You can technically remove the license file, but it is released under this license, anyways. Changing the license would mean that the current state is available under two licenses. New changes would be available under the corrected license only.

Even if the JSR detail page says different things, the license in the code is the effective one. There is nothing I can find that links from the TCK to the detail page, so there is no way that the detail page can be legally effective.

That means, you cannot "just" change the license now without consent of all contributors and/or Oracle. If everything is covered by the OCA, Oracle could do so on its own.

Why not change the detail page for consistency? 

What is the issue? Is there a contributor not happy with the Apache license, since he/she only agreed to the license on the detail page?

**Comment by keilw** [comment]
I don't think you can "update the detail page" for a final JSR. It's a question of transparency to make the correct TCK license available and known before the JSR goes final. And other than the commercial (Oracle) TCK license, it says

As required by the Java Specification Participation Agreement (JSPA), the TCK will be licensed at no charge without support to qualified not-for-profit. The Compatibility Testing Scholarship Program will verify such qualification. Support may also be provided at no charge with approval of the scholarship board. For more information, please refer to:
http://www.oracle.com/technetwork/java/index-137188.html

That does not sound to me like it's "automatically Apache licensed". For a MR of this JSR and TCK you might be able to change it, but for 1.0 I suppose it's under the licenses stated on the detail page. I am not aware that you could do so retroactively, but in a MR if the EC doesn't object you should be able to fix that.

**Comment by cruftex** [comment]
> It's a question of transparency to make the correct TCK license available and known before the JSR goes final.

Totally agree. But for some reason it didn't happen this way and there is no way to get it undone. 

> I don't think you can "update the detail page" for a final JSR.

Isn't changing to a less restrictive license possible in an MR? That would seam common sense to me. Can you check with the EC on this?

Would it be alternatively okay for you that the RI and TCK will be released under the JSPA Licence and the Apache license jointly?

**Comment by keilw** [comment]
According to EG members from JSRs like CDI at JavaLand right now, their understanding is, that especially source code headers in Java files mean, that's the applicable license. Either way, the Spec Lead(s) must get this sorted and if the JCP.org detail page was wrong/mislead (PMO said, they had heard what  's now on https://jcp.org/en/jsr/detail?id=107 3 years ago) then it should be fixed ASAP. This JSR upgraded to JCP 2.9 which means it has to fulfil certain transparency requirements. And that's not the case, if only RI mentions Apache 2.0 but for the TCK it says something completely different.

**Comment by cruftex** [comment]
For the API jar, there is also a (new) license discussion:
https://github.com/jsr107/jsr107spec/issues/333

+1 for sorting it out!

**Comment by keilw** [comment]
Looks like I'm not the only one interested in these things.
Gone through a lot of similar troubles when JSR 363 was requested for Eclipse Orbit inclusion. And I can assure you, Eclipse would not accept JSR 103 with the current license file either ;-)

**Comment by gregrluck** [comment]
Werner, the TCK must be licensed under the TCK license. But the TCK is not these tests. You download the TCK from the JCP. We make the tests that are included in it available under Apache 2.

**Comment by keilw** [comment]
So you're saying you do the same "Dual License" as e.g. CDI does even for the entire Spec? (a rather unique thing for them given what all other specs do)

**Comment by gregrluck** [comment]
Werner, the Spec license is different. We have a standard spec license.

The Junit tests are Apache 2. There is more to the TCK than that. For example the TCK User Guide.

**Comment by keilw** [comment]
Yes but the TCK should have a license (or licenses) as stated on the JSR detail page. 
According to the detail page it's the special "Oracle TCK license", not Apache, if it can be dual-licensed, then why not state it? I know that'll be a big show-stopper for many EE JSRs and for the EC's offer to help. I mentioned it could be taken as an example for Spec Lead sharing, but we also heard, licensing is out of question for Oracle, hence there may be a "collaborative" way to develop the RI and even TCK, but (at least where Oracle is involved) no Open Source TCK. CDI is transparent and consistent on that;-) https://jcp.org/en/jsr/detail?id=365

**Comment by keilw** [comment]
JMS 2.1 like many other EE JSRs offer multiple TCK licenses:https://jcp.org/en/jsr/detail?id=368
Whether you could only have "2. Non-Commercial use" for Apache or something else, you should be able to explore, but try to be transparent whenever filing something new (might be a bit harder with a MR but you did apply JCP 2.9 here, too;-)

**Comment by cruftex** [comment]
I always want to make thing right, but I think I did a mistake here to open the conversation.

Germans are known to be very picky about details. For myself, that is true, for sure.

Transparency: Everything is released and public. Done.

Different licenses: This might be an inconsistency. But:

Reading you comments above, you found all the licenses and you found out where they are applicable. Every information was available to you.

Nobody that wants to use the RI or the TCK cannot do this, because of a missing _license grant_ that should be there.

Nobody is affected. Unless this changes, we should move on and do a great API!

**Comment by keilw** [comment]
It's not about Germans (which in fact I'm not;-) but the JCP and EC trying to make things more transparent for users of those JSRs. From a "GitHub community" point it's sure done as many usually don't care about jcp.org or the process. Since a JSR is final there is no need to change that until it publishes anything new, which see the API license and file headers they must do before e.g. any Eclipse project would be able to use it (been  there with 363 in fact the IP team is still  working on it after the change;-)
