### ISSUE TITLE
Invalid assertion on call to CacheManager.getCacheNames() when CacheManager isClosed.

### ISSUE THREAD

**Issue by jfialli** [jsr107/jsr107tck#87]
### TCK Challenge:

Call to CacheManager.getCacheNames() on a closed CacheManager should
assert IllegalStateException is thrown.  Invalid test is asserting that the methods
returns an empty iterator.

Per page 39 of the specification and the javadoc for CacheManager.getCacheNames(), after a CacheManager has been closed, any operational method will throw an IllegalStateException.
The operational methods on CacheManager are: createCache, destroyCache, enableManagement, enableStatistics, getCache and getCacheNames.

### Proposed resolution:
Add  @Test(expected = IllegalStateException.class) to CacheManagerTest.close_cachesEmpty()
and change the following line in the method 

From:
`    assertFalse(cacheManager.getCacheNames().iterator().hasNext());
`
To:
`    cacheManager.getCacheNames();
`

**Comment by cruftex** [comment]
+1, existing implementations need to change their behavior

Will prep a PR.

**Comment by gregrluck** [comment]
Fixed. Also had to fix a failing test in CacheManagerManagementTest
