### ISSUE TITLE
CacheManagerTest#getCaches_MutateReturn is invalid in regards to JCache Spec 1.0

### ISSUE THREAD

**Issue by jfialli** [jsr107/jsr107tck#88]
The test asserts that UnsupportedOperationException is thrown for the following:

      cacheManager.getCacheNames().iterator().remove();

But the jsr107 1.0 specification (pg 24) and  CacheManager.getCacheNames javadoc explicitly states that IllegalStateException must be thrown when remove is called on the Iterator over an immutable collection.

### Proposed Resolution: 

1. Mark this test as invalid until specification issue jsr107/jsr107spec#334 is resolved in a maintenance specification release.

2. When the test is reinstated, the code should be changed to the following;
    
`Iterator<String> iter = cacheManager.getCacheNames().iterator();
iter.next();
iter.remove();`

The existing code *could* throw IllegalStateException due to remove() being called before 
iter.next() has been called. (Based on Iterator.remove() javadoc).

**Comment by cruftex** [comment]
for 1:

The Spec is obviously wrong, the existing test helps implementing code that makes sense. Let's keep it.

for 2:

It is always `UnsupportedOperationException`, it can't be both. So yours and the existing variant needs to yield `UnsupportedOperationException`.

Do you have code that is impacted if we keep this as is?

**Comment by jfialli** [comment]
No

**Comment by gregrluck** [comment]
Jo, I accept this is a valid TCK challenge. I cannot see us putting out a TCK update ahead of 1.1, so I have fixed this in 1.1.
