### ISSUE TITLE
Concurrency related tests

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107tck#89]
#### Goal

Very basic tests of concurrency issues of CAS operations and listeners.

#### Non Goal

Comprehensive stress test suite.

#### Idea

Explore, whether it is possible to do short running tests by introducing some arbitration within the listeners

**Comment by cruftex** [comment]
I checked the RI and I think we could add some tests for atomicy, since the RI
puts locks around the operation via:

````
lockManager.lock(key);
try {
...
} finally {
  lockManager.unLock(key);
}
````

I think some basic checks seam feasible.

Improving the TCK in the regard is low priority and we should try to be as deterministic as possible and
don't extend the runtime very much.

**Comment by gregrluck** [comment]
@cruftex we decided to not create a thread safe RI and not to test implementations for thread safety.
