### ISSUE TITLE
classloader checks / cleanup app-domain.jar / test-domain.jar

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107tck#92]
The Spec says on page 20:

> A CacheManager provides: [ ... ]  The ClassLoader that caches will use, should they require it,
> for resolving and loading application classes.

I browsed through the TCK and cannot find any assertions for this. There is a jar file called `app-domain.jar` that seams to be created for it. This gets picked up in `CachingProviderClassLoaderTest`. But there is no test with it. Did I miss something?

Should we:
1. Remove `app-domain.jar` and leave classloading untested?
2. Add tests?

**Comment by vbekiaris** [comment]
It looks like there was a test for `Cache`s with different `ClassLoader`s that did actually use `app-domain.jar` artifact but was removed by https://github.com/jsr107/jsr107tck/commit/3e9623342b3155db8620864d161f83530703f108 as a fix for https://github.com/jsr107/jsr107tck/issues/56 . My understanding is that tests should be added to verify classloading behaviour of `Cache`s.

**Comment by cruftex** [comment]
Meanwhile I found out that the beans in `app-domain.jar` are used in some other tests. However, those tests don't need it in a separate class.

The whole classloading topic is in https://github.com/jsr107/jsr107spec/issues/358 and was deferred to JCache 2.0. We shouldn't add tests if the Spec is not clear about it.

If the TCK 1.1 is also uploaded to maven central, I think we should cleanup and put the needed code from these modules in the TCK directly. app-domain.jar and test-domain.jar on maven central is looking quite strange.
