### ISSUE TITLE
Java version should be 1.6

### ISSUE THREAD

**Issue by cruftex** [jsr107/jsr107tck#94]
The Spec targets Java 1.6. The TCK is for 1.7:

````
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
````

How can we test an implementation on 1.6?

I don't have an impact and probably nobody else, but it is wrong. If it is an easy fix, we should do it.

**Comment by gregrluck** [comment]
The TCK Users Guide states the the TCK requires 1.7 or higher. 

You can test an implementation written in 1.6

**Comment by jerrinot** [comment]
so JSR107 TCK cannot be used to validate a provider works well when Java 1.6 is used in runtime? That's a shame. What's the reason for this constraint?

**Comment by brianoliver** [comment]
When JCache was released, Java 6 was end-of-life.   It was decided (by the community) that the JCache TCK should be using a modern (Java 7 at the time) release, instead of a release of Java that was no longer publicly supported.  

More specifically, it would be unfair for the community (and vendors) to potentially license (ie: pay) for a version of Java that was end-of-life, especially to develop a new product.

Note: Java 7 is also now end-of-life.

**Comment by jerrinot** [comment]
Thanks for explanation!

I would argue a specific implementation of Java 6 from a particular vendor was end-of-life, but I understand your point. 

However now the situation is that JCache API is targeting Java 6, but there is no easy(?) way validate a provider is actually passing the tests when Java 6 runtime is used (without tinkering with TCK)

Isn't it possible to expose TCK artefacts compiled with Java 6 , but still use Java 7 in runtime during official TCK tests?

**Comment by brianoliver** [comment]
> I would argue a specific implementation of Java 6 from a particular vendor was end-of-life, but I 
> understand your point.

You're right.  It raises an interesting question, for which I don't know the answer.   eg: What releases/vendors or Java should JCache support?   I'm not sure if there's any requirement or documentation for that.   I think everyone naturally assumes Oracle distribution of Java (hence EOL).

Perhaps we can continue this conversation as a separate topic on the Google Forum?

> However now the situation is that JCache API is targeting Java 6, but there is no easy(?) way validate
> a provider is actually passing the tests when Java 6 runtime is used (without tinkering with TCK)

I understand.  At the same time, everyone is in the same boat.   Furthermore from recent surveys very few people are targeting new / upgrading applications to use JCache and Java 6.   Hence Java 7 was the natural choice.

> Isn't it possible to expose TCK artefacts compiled with Java 6 , but still use Java 7 in runtime during
> official TCK tests?

It's probably possible.  The question is investment and priority.   We all have limited cycles to contribute and maintain these things so refactoring tests (say) to run on Java 6, when the community agreed Java 7 was all that was required would have to fit in with other maintenance work and possibly future work.   Given no one (perhaps apart from yourself) has suggested it, perhaps it won't become a high priority?

Perhaps we can continue this conversation as a separate topic on the Google Forum?

**Comment by jerrinot** [comment]
@brianoliver: I'm fine with this explanation.
I understand it's not a priority and I can certainly see why. 

Once more thanks!

**Comment by cruftex** [comment]
@brianoliver 

> I'm not sure if there's any requirement or documentation for that.

Well a Java Specification (Request) can only target other specifications, not implementations. Otherwise the concept of a specification would become very obscure in itself ;)
