### ISSUE TITLE
TCK CacheLoaderTest requires CacheLoaderException but API says CacheException

### ISSUE THREAD

**Issue by christian-esken** [jsr107/jsr107tck#99]
The CacheLoaderTest has two tests, that check if CacheLoaderException is thrown: 
- shouldPropagateExceptionUsingLoadAll()
- shouldPropagateExceptionUsingGet()

Issue: These tests contrast the Javadocs, which state for Cache.loadAll()
 - 1) "If a problem is encountered during the retrieving or loading of the objects,  an exception is provided to the {@link CompletionListener}." (no special exception type mentioned)
 - The @throws declaration is "@throws CacheException        thrown if there is a problem performing the load."
 - The JSR107 Spec itself contains CacheLoaderException in the CacheLoader (only 4 times), and does not mention any wrapping requirements.
	
Proposed change:
 Change the two test cases to check for CacheException.

**Comment by cruftex** [comment]
The JavaDoc in the `CacheLoaderException` says:

> A Caching Implementation must wrap any {@link Exception} thrown by a {@link
> CacheLoader} in this exception.

A `CacheLoaderException` is a `CacheException`, so the throws declaration is correct.
It is just needs to be wider, since there may be other problems not originated by the loader directly.

**Comment by christian-esken** [comment]
OK, I see. Then it is more just an omission in the Spec document (v1.0). Which is way better than an actual issue. :-) If it is in the JavaDoc, it should be added to the Spec document. Thus I propose the following:
- Add the CacheLoaderException JavaDoc to the JSR107 Spec
- About the Cache.loadAll() JavaDocs. Even though the throws declaration is technically correct, I find it confusing and would like to see CacheLoaderException explicitly mentioned.

**Comment by cruftex** [comment]
> About the Cache.loadAll() JavaDocs. Even though the throws declaration is technically correct, I find it confusing and would like to see CacheLoaderException explicitly mentioned.

`loadAll()` is an asynchronous operation. A loader exception is signaled via the `CompletionListener`.
Actually, `loadAll` should never throw a `CacheLoaderException` directly.

The documentation on the `CompletionListener` is quite sparse. Actually, as a user, I would not expect it to be a `CacheLoaderException` always, because there is no need to wrap, when not thrown.

**Comment by cruftex** [comment]
Found more related stuff in the Spec and created an issue for that. Needs investigation.
Closing this. Good looking at this.
